#!/usr/bin/env bash
set -e

JIRA_TICKET=$(git branch --show-current | cut -d '/' -f1)
TITLE=$(git branch --show-current | cut -d '/' -f2 | sed -e 's/-/ /g')

if [ -z "$JIRA_TICKET" ] || [ -z "$TITLE" ] || [ ! -f .github/PULL_REQUEST_TEMPLATE.md ]; then
  echo "I don't think you are in a branch with a JIRA ticket name"
  exit 1
fi

TEMPLATE=$(cat .github/PULL_REQUEST_TEMPLATE.md | sed -e 's/ticketnumber/'$JIRA_TICKET'/g')

gh pr create -d --title "[$JIRA_TICKET] $TITLE" --body "$TEMPLATE"
